### ISSUE TITLE
Log messages about array dtype conversion

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/freud#265] opened 2019-05-07 00:59 UTC
My logs are overflowing with messages produced here:
https://github.com/glotzerlab/freud/blob/8bb083f03086f41e94abcbad6fd93a2d10f4d703/freud/common.py#L47-L50

What is the purpose of this message? Is it a warning about potential performance issues? A `UserWarning` might be more appropriate then. Is it this information pertinent to debugging? Then I suggest to demote it to a lower logging-level.

**Comment by vyasr** [comment] 2019-05-07 03:07
Currently this function doesn't assume a dtype, but essentially every single call to it (which is every input array in freud AFAIK) asks for conversion to a `numpy.float32`. I suspect that it was introduced when the decision was first made to make freud single precision, so that initially at least it was an important thing to note which features were converting arrays from 64- to 32-bit. We can probably just remove the log at this point and just make sure that's clear in the overall documentation that everything in freud is in single precision (for the moment).

**Comment by bdice** [comment] 2019-05-07 12:41
I would be okay with changing this to a `UserWarning` - but I want it to be quieter, not louder. I don't see this message very often, and I'm guessing that you see it a lot because you have your logger set to a fairly high verbosity. I would not want the change to a `UserWarning` to make it appear for all users.

@csadorf Would you be willing to contribute a PR?

**Comment by csadorf** [comment] 2019-05-07 13:49
> I would be okay with changing this to a `UserWarning` - but I want it to be quieter, not louder. I don't see this message very often, and I'm guessing that you see it a lot because you have your logger set to a fairly high verbosity. I would not want the change to a `UserWarning` to make it appear for all users.
> 
> @csadorf Would you be willing to contribute a PR?

Yes, but your comment is ambiguous. What exactly do you want me to do?

**Comment by vyasr** [comment] 2019-05-07 14:23
@bdice I'm also not quite certain what you want to do. I'm also not sure what the "correct" behavior for this is. In principle, a Warning makes more sense to me than a log entry since this is something that the user can do something about (explicitly pass in `np.float32` arrays). In practice, everyone is using the default `numpy` array dtype, which is `np.float64`, and there isn't much reason to expect that to change since I doubt the loss in precision is affecting anyone. That being the case, my inclination would be to move this to `logging.DEBUG` level.

We should also make a couple other changes. The `dtype` argument should default to `numpy.float32`, and contiguous should default to `True` (if that argument even needs to be an option). That way, we don't have to replicate this behavior throughout all calls to the function in `freud`. Moreover, if we get around to supporting variable precision, we would only need to set that flag here.

**Comment by bdice** [comment] 2019-05-07 14:52
Apologies for the ambiguity, I may not fully understand the implications of changing to a `UserWarning`. I expected that a warning is louder than info (it shows at a "quieter" setting of verbosity), but it only shows once? Is that right?

In any case, I'll defer to @vyasr's thoughts on this.

**Comment by vyasr** [comment] 2019-05-07 15:13
You're right that instances of `warnings.warning` typically only show up once. Repeated instances of the same warning are usually suppressed by design of the `warnings` module. However, warnings from that module are also unaffected by the verbosity level of the logger, because they are managed from a completely separate system, so if we switched to `warnings.warning` then every user would always see this (unless they import the module and manually override warnings). So in summary, it is louder and only shows up once, but cannot be suppressed without jumping through some additional hoops. Does that make sense?

Since there's no reason for users to think something is wrong just because this conversion is happening, I don't think making this harder to suppress makes sense, even if it reduces the frequency. My two suggestions were to lower the logging level to make it quieter (from `logger.info` to `logger.debug`, which is the lowest available level), or to remove it altogether. I could imagine a scenario where users expected double precision and it caused problems for them, which would be the main reason to retain debug level logging. On the other hand, since all of freud is single precision I also think we should just do a better job of warning about this on the documentation and skip all warnings in the code. I could go either way on that, what do you think?

**Comment by bdice** [comment] 2019-05-07 15:18
Thanks for the clarification @vyasr. My concern was that switching to a `UserWarning` would make it appear for all users once (who currently see it zero times) even though it would help with @csadorf's problem of seeing it many times at info-level logging.

I vote to remove the message entirely and note in our docs that `freud` is single-precision. That should be noted anyway.

**Comment by vyasr** [comment] 2019-05-07 15:23
I concur, that is the most reasonable given how freud works right now. @csadorf that makes this PR very simple :)

**Comment by csadorf** [comment] 2019-05-07 15:24
> I concur, that is the most reasonable given how freud works right now. @csadorf that makes this PR very simple :)

Where do you want the note in the documentation?

**Comment by vyasr** [comment] 2019-05-07 15:28
Hmm that's a good question. Since the documentation is entirely API documentation at the moment, there isn't a great place for it. If you saw our RTD, where would you expect to find it? The best option we have may be putting it directly in the Overview (e.g. "freud uses single-precision NumPy arrays..."), or as a note in the Examples section.

**Comment by csadorf** [comment] 2019-05-07 15:30
On the index page:

> The freud library uses **single-precision** NumPy arrays for input and output,

**Comment by csadorf** [comment] 2019-05-07 15:30
Lol, apparently I didn't read your comment closely enough. :D

**Comment by vyasr** [comment] 2019-05-07 15:30
Right, that's the Overview I meant :)

**Comment by csadorf** [comment] 2019-05-07 15:31
Ok, I'll make the PR.

**Comment by bdice** [comment] 2019-05-24 02:41
Resolved by #267.

**Closed as completed by bdice** 2019-05-24 02:41 UTC
